dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - openZeppelin/openzeppelin-contracts@4.6.0

compiler:
  solc:
   remappings:
    - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
    - '@openzeppelin=openZeppelin/openzeppelin-contracts@4.6.0'

networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  bsc_test_moralis:
    eth_usd_price_feed: '0x143db3CEEfbdfe5631aDD3E50f7614B6ba708BA7'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False